name: Unity Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    name: Generate Unity Activation File
    runs-on: ubuntu-latest

    steps:
      - name: Generate activation file
        id: activation
        uses: webbertakken/unity-request-manual-activation@v1
        with:
          unityVersion: 6000.3.11f1

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: ${{ steps.activation.outputs.filePath }}
